[ 2025-02-20 20:36:56,332 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-02-20 20:36:56,333 ] root - INFO - Getting the data from mongodb
[ 2025-02-20 20:36:56,334 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-02-20 20:36:56,335 ] root - INFO - Exporting data from mongodb
[ 2025-02-20 20:36:57,841 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "message": "Starting topology monitoring"}
[ 2025-02-20 20:36:57,842 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: []>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
[ 2025-02-20 20:36:57,843 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "message": "Starting server monitoring"}
[ 2025-02-20 20:36:57,844 ] pymongo.connection - DEBUG - {"clientId": {"$oid": "67b7451165793033d0bccee5"}, "message": "Connection pool created", "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017}
[ 2025-02-20 20:36:57,849 ] root - INFO - MongoDB connection successful.
[ 2025-02-20 20:36:57,851 ] pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "67b7451165793033d0bccee5"}}
[ 2025-02-20 20:36:57,852 ] pymongo.serverSelection - DEBUG - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "67b7451165793033d0bccee5"}, "remainingTimeMS": 30}
[ 2025-02-20 20:36:57,984 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 140.99999982863665, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:36:57,985 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:36:58,486 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:36:58,487 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:36:58,989 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:36:58,989 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:36:59,492 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:36:59,493 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:36:59,994 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:36:59,995 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:00,498 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:00,499 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:01,001 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:01,002 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:01,504 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:01,505 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:02,082 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 77.9999999795109, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:02,082 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:02,585 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:02,586 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:03,088 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:03,089 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:03,597 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:03,597 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:04,100 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:04,100 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:04,602 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:04,603 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:05,105 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:05,106 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:05,608 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:05,609 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:06,111 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:06,112 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:06,614 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:06,614 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:07,194 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 77.9999999795109, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:07,195 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:07,697 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:07,698 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:08,200 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:08,201 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:08,703 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:08,703 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:09,205 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:09,205 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:09,709 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:09,709 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:10,211 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:10,212 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:10,714 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:10,715 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:11,216 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:11,217 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:11,719 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:11,720 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:12,307 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 77.9999999795109, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:12,308 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:12,810 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:12,811 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:13,314 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:13,315 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:13,816 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:13,817 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:14,319 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:14,320 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:14,822 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:14,822 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:15,325 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:15,326 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:15,828 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:15,829 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:16,331 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:16,332 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:16,834 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:16,835 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:17,413 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 77.9999999795109, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:17,415 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:17,917 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:17,918 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:18,420 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:18,420 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:18,923 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:18,924 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:19,425 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:19,426 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:19,929 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:19,930 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:20,430 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:20,432 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:20,933 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:20,934 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:21,437 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 15.999999828636646, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:21,437 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:21,940 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:21,940 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:22,633 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 188.0000000819564, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:22,634 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:23,136 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:23,137 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:23,639 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:23,639 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:24,141 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:24,142 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:24,644 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:24,646 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:25,148 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:25,148 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:25,650 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:25,651 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:26,153 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:26,154 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:26,657 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:26,658 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:27,245 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 77.9999999795109, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:27,245 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:27,748 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:27,749 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:28,251 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "serverHost": "cluster0.5pwaq.mongodb.net", "serverPort": 27017, "awaited": false, "durationMS": 0.0, "failure": "\"AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')\"", "message": "Server heartbeat failed"}
[ 2025-02-20 20:37:28,251 ] pymongo.topology - DEBUG - {"topologyId": {"$oid": "67b7451165793033d0bccee5"}, "previousDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "newDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "message": "Topology description changed"}
[ 2025-02-20 20:37:28,252 ] pymongo.serverSelection - DEBUG - {"message": "Server selection failed", "selector": "Primary()", "operation": "find", "topologyDescription": "<TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>", "clientId": {"$oid": "67b7451165793033d0bccee5"}, "failure": "\"cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)\""}
[ 2025-02-20 20:37:28,253 ] root - ERROR - Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\data_access\proj1_data.py] at line number [49]: cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[ 2025-02-20 20:37:28,255 ] root - ERROR - Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [35]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\data_access\proj1_data.py] at line number [49]: cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[ 2025-02-20 20:37:28,257 ] root - ERROR - Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [35]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\data_access\proj1_data.py] at line number [49]: cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[ 2025-02-20 20:37:28,259 ] root - ERROR - Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\pipline\training_pipeline.py] at line number [45]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [35]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\data_access\proj1_data.py] at line number [49]: cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[ 2025-02-20 20:37:28,262 ] root - ERROR - Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\pipline\training_pipeline.py] at line number [131]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\pipline\training_pipeline.py] at line number [45]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\components\data_ingestion.py] at line number [35]: Error occurred in python script: [C:\Users\sanch\OneDrive\Desktop\data\vehicle MLops\src\data_access\proj1_data.py] at line number [49]: cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67b7451165793033d0bccee5, topology_type: Unknown, servers: [<ServerDescription ('cluster0.5pwaq.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('cluster0.5pwaq.mongodb.net:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
